# Generated by Django 5.2.3 on 2025-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_volunteerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
