# Generated by Django 5.2.3 on 2025-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parthnerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_company', models.CharField(max_length=100)),
                ('field_of_activity', models.CharField(max_length=100)),
                ('size_of_company', models.CharField(blank=True, max_length=200, null=True)),
                ('website_company', models.CharField(blank=True, max_length=200, null=True)),
                ('description_of_company', models.TextField(blank=True, max_length=500, null=True)),
                ('type_of_partnership', models.CharField(max_length=100)),
                ('budget', models.CharField(blank=True, max_length=150, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_information', models.TextField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ParthnerApplication',
        ),
    ]
