# Generated by Django 5.2.3 on 2025-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_partnerapplication_delete_parthnerapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry',
            field=models.CharField(default='00/00', max_length=5),
        ),
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
