# Generated by Django 5.2.3 on 2025-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_donation_options_remove_donation_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
