# Generated by Django 5.2.3 on 2025-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_donation_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Заявка волонтера', 'verbose_name_plural': 'Заявки волонтерів'},
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='rules_consent',
            field=models.BooleanField(default=False),
        ),
    ]
