# Generated by Django 5.2.3 on 2025-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое, на украинском'),
        ),
    ]
