# Generated by Django 5.2.3 on 2025-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_content_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок, на украинском'),
        ),
    ]
